# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  appenders:
   - type: console
     logFormat: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%t] --- %-36(%X{X-Request-ID:-NO-REQUEST-ID}): %-40.40logger{39} :  %msg%n'



server:
  rootPath: /api/


mongo:
  host: localhost
  port: 27017