# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO



server:
  rootPath: /api/


mongo:
  host: localhost
  port: 27017